### ISSUE TITLE
numpy 2.0: masked arrays cast right of product to ndarray

### ISSUE THREAD

**Issue by fipymigrate** [usnistgov/fipy#207]
In present numpy
masked_array \* fipy_variable 
leads to fipy_variable.**ldiv**(masked_array), which returns a binary operator.

In upcoming fipy however it leads to a ndarray.
That is, in
http://projects.scipy.org/numpy/browser/trunk/numpy/ma/core.py
get_data function has changed to: 

try:
data = a._data
except AttributeError:
data = np.array(a, copy=False, subok=subok)

so a cast is tried to np.array on fail. A fipy_variable can be cast to array, so we end up with using
masked_array.**div**(fipy_variable)

This breaks the intended way variables should behave in a multiplication.

In attachment a test file for this bug, with old=True, a crash happens, for old=False, all is ok because order of calling has changed. 

The bug output:
  File "diftermerror.py", line 18, in <module>
print 'coval', type(coeff), type(coeff.getValue())
AttributeError: 'MaskedArray' object has no attribute 'getValue'

 _Imported from trac ticket [#303](http://www.ctcms.nist.gov/cgi-bin/redirectLegacyMatforge.py?url=http://matforge.org/fipy/ticket/303),  created by benny.malengier@gmail.com on 07-16-2010 at 14:41, last modified: 05-09-2011 at 12:27_

**Comment by guyer** [comment]
Works with numpy 1.10.4
