### ISSUE TITLE
Example mesh1D.py not working on ubuntu 11.04

### ISSUE THREAD

**Issue by fipymigrate** [usnistgov/fipy#263]
Downloaded python-fipy_2.1.2-1_all.deb from http://www.matforge.org/fipy/downloader/download/notes/file/56 and installation went smoothly.  Running Ubuntu 11.04 64-bit (Natty Narwhal).  Download examples from repository and ran `python examples/diffusion/mesh1D.py` .  Received the error: 
AttributeError: 'CellVariable' object has no attribute 'constrain'

This occurs at the line phi.constrain(valueRight, mesh.facesRight).  I printed dir(phi) and it seems that constrain is not a member function of phi.

 _Imported from trac ticket [#359](http://www.ctcms.nist.gov/cgi-bin/redirectLegacyMatforge.py?url=http://matforge.org/fipy/ticket/359),  created by bzaitlen on 09-09-2011 at 11:04, last modified: 09-19-2011 at 16:19_
