### ISSUE TITLE
Strange deprecation loop in reshape()

### ISSUE THREAD

**Issue by guyer** [usnistgov/fipy#407]
As reported on [StackOverflow](http://stackoverflow.com/questions/20927397/numpy-typeerror-reshape-got-an-unexpected-keyword-argument-order), there's something strange about the deprecation of `CellVariable.reshape()`.

 _Imported from trac ticket [#664](http://www.ctcms.nist.gov/cgi-bin/redirectLegacyMatforge.py?url=http://matforge.org/fipy/ticket/664),  created by guyer on 01-27-2014 at 18:30, last modified: 01-27-2014 at 18:30_

**Comment by guyer** [comment]
```python
DeprecationWarning: :func:`reshape` is deprecated, use :func:`numerix.reshape()<numpy.reshape>` instead!
return reshape(newshape, order=order)
Traceback (most recent call last):
File "./render2.py", line 374, in <module>
,u=np.reshape(voltage.grad[0], (ny, nx))
File "/home/jana/Builds/lib/python2.6/site-packages/numpy/core/fromnumeric.py", line 172,  in reshape
return reshape(newshape, order=order)
File "/home/jana/Builds/lib/python2.6/site-packages/fipy/tools/decorators.py", line 151, in newfunc
return func(*args, **kwds)
TypeError: reshape() got an unexpected keyword argument 'order'
```

**Comment by guyer** [comment]
Addressed by #454?

**Comment by guyer** [comment]
The issue cited on StackOverflow seems to work with FIPy 3.1.3 and numpy 1.10.4
