### ISSUE TITLE
module 'petsc4py.PETSc' has no attribute 'COMM_SELF'

### ISSUE THREAD

**Issue by ODupon** [usnistgov/fipy#1099]
Hello

For our simulation model, we are using fipy to solve it. However, this is going very slow. It takes 15 minutes for each hourly timestep and we need to simulate for several days. So we are currently looking into improving the speed of the solver. 

Currently we're working on python >3.8 and we've been trying to apply pysparse and PETSc. We can's seem to install the former, but we managed to install PETSc, but when trying to run we receive the following error from the fipy module:

`  
  File "/tmp2/olivier.dupon/miniconda3/lib/python3.8/site-packages/fipy/solvers/petsc/__init__.py", line 5, in <module>
    from fipy.solvers.petsc.linearLUSolver import *
  File "/tmp2/olivier.dupon/miniconda3/lib/python3.8/site-packages/fipy/solvers/petsc/linearLUSolver.py", line 8, in <module>
    from fipy.solvers.petsc.petscSolver import PETScSolver
  File "/tmp2/olivier.dupon/miniconda3/lib/python3.8/site-packages/fipy/solvers/petsc/petscSolver.py", line 7, in <module>
    from fipy.matrices.petscMatrix import _PETScMeshMatrix
  File "/tmp2/olivier.dupon/miniconda3/lib/python3.8/site-packages/fipy/matrices/petscMatrix.py", line 484, in <module>
    class _PETScMatrixFromShape(_PETScMatrix):
  File "/tmp2/olivier.dupon/miniconda3/lib/python3.8/site-packages/fipy/matrices/petscMatrix.py", line 488, in _PETScMatrixFromShape
    matrix=None, comm=PETSc.COMM_SELF):
AttributeError: module 'petsc4py.PETSc' has no attribute 'COMM_SELF'
`

Do you have any idea how to resolve this. Is my PETSc build faulty?

Kind regards
Olivier Dupon

**Comment by guyer** [comment]
Was PETSc built with MPI support? Do you have mpi4py installed.

I strongly recommend using conda to obtain these packages, rather than trying to build them yourself.

Be aware that PySparse tends to be our fastest performing solver, even though it's very obsolete.

I am close to releasing a new version of FiPy that should have much better performance for PETSc, but if PySparse is too slow for you, then you're still probably not going to be happy.

Is there any particular reason you chose LU? It tends not to be fast. 

How big is your system?

**Comment by ODupon** [comment]
I would love to use PySparse for this, but as far as I know it's only usable on a python 2.7 environment. Sadly, our system is only usable on python 3.x. If I'm wrong, any advice on getting PySparse to work would be great!

In regards to PETSc, I tried to build it with conda initially, but ran into problems. I have installed mpi4py. 

Regarding LU, I tried running the different solvers available within the fipy.scipy package, but sadly they didn't manage or were far slower than LU. 

Uhm about the size, I'm not sure how to best describe it for you that helps. In general, the solver sweeps over 5 following coupled equations:

`self.POISSON_EQ = fp.DiffusionTerm(
            coeff=-2.0 * (self.EPSILON**2), var=self.PHI
        ) == (
            (
                fp.ImplicitSourceTerm(coeff=-1.0, var=self.N)
                + fp.ImplicitSourceTerm(coeff=1.0, var=self.P)
                + self.DOPING
                + fp.ImplicitSourceTerm(coeff=1.0, var=self.CA)
                + fp.ImplicitSourceTerm(coeff=-1.0, var=self.AN)
            )
        )  # + self.RHO_DEFECTS ))
        # + fp.ImplicitSourceTerm(coeff=1,var=self.RHO_DEFECTS) ))

        P_correction = self.NV / (self.NV - (self.dev.gamma * self.P.value))
        self.P_CONTINUITY_EQ = (
            fp.TransientTerm(coeff=self.trasient_state, var=self.P)
            == fp.DiffusionTerm(coeff=self.DP * P_correction, var=self.P)
            + fp.ConvectionTerm(
                coeff=(
                    self.DP * P_correction * (self.PHI.grad - self.IP.grad.value[0])
                ),
                var=self.P,
            )
            - self.r_total * self.norm_parameters.tau0 / self.norm_parameters.n0
            + fp.ConvectionTerm(
                coeff=((self.DP * P_correction) / self.NV) * self.NV.grad, var=self.P
            )
            + self.r_gen * self.norm_parameters.tau0 / self.norm_parameters.n0
        )  # +  \
        # (self.MESH.facesRight * self.BC_JP_R).divergence + (self.MESH.facesLeft * self.BC_JP_L).divergence #

        N_correction = self.NC / (self.NC - (self.dev.gamma * self.N.value))
        self.N_CONTINUITY_EQ = (
            fp.TransientTerm(coeff=self.trasient_state, var=self.N)
            == fp.DiffusionTerm(coeff=self.DN * N_correction, var=self.N)
            + fp.ConvectionTerm(
                coeff=(
                    -self.DN * N_correction * (self.PHI.grad - self.EA.grad.value[0])
                ),
                var=self.N,
            )
            - self.r_total * self.norm_parameters.tau0 / self.norm_parameters.n0
            + fp.ConvectionTerm(
                coeff=((self.DN * N_correction) / self.NC) * self.NC.grad, var=self.N
            )
            + self.r_gen * self.norm_parameters.tau0 / self.norm_parameters.n0
        )  # + \
        # (self.MESH.facesLeft * self.BC_JN_L).divergence +  (self.MESH.facesRight * self.BC_JN_R).divergence #

        AN_correction = 1  # self.a_max/(self.a_max - self.AN.value)
        CA_correction = 1  # self.c_max/(self.c_max - self.CA.value)
        self.AN_CONTINUITY_EQ = fp.TransientTerm(
            coeff=self.trasient_state, var=self.AN
        ) == fp.DiffusionTerm(
            coeff=self.DAN * AN_correction * self.AN_accelerator, var=self.AN
        ) - fp.ConvectionTerm(
            coeff=(self.DAN * self.AN_accelerator * (self.PHI.grad)), var=self.AN
        )
        self.CA_CONTINUITY_EQ = fp.TransientTerm(
            coeff=self.trasient_state, var=self.CA
        ) == fp.DiffusionTerm(
            coeff=self.DCA * CA_correction * self.CA_accelerator, var=self.CA
        ) + fp.ConvectionTerm(
            coeff=(self.DCA * self.CA_accelerator * (self.PHI.grad)), var=self.CA
        )
        self.COUPLED_EQ = (
            self.POISSON_EQ
            & self.P_CONTINUITY_EQ
            & self.N_CONTINUITY_EQ
            & self.AN_CONTINUITY_EQ
            & self.CA_CONTINUITY_EQ
        )`

Each coefficient used within the terms uses a Grid1D mesh. In the end it's over the COUPLED_EQ the sweep is done with the provided solver. In this case the LU one. 

To be honest, I inherited this code from a colleague who left recently and my company is putting the screws on me to improve it, so I'm only slowly starting to understand the details of it. So apologies if I'm not complete in my explanations.

**Comment by guyer** [comment]
No, PySparse is not viable. I've been trying to get rid of Python 2.7 support for some time now. I only brought it up because the next release brings the other solvers on par with PySparse, so if PySparse is too slow for you, you will likely be unhappy with the other choices. SciPy, in general, is the slowest of the bunch.

As to the size, it's helpful to know that you have five coupled equations, but I mostly wanted to know the dimensions of your mesh.

> In regards to PETSc, I tried to build it with conda initially, but ran into problems.

Can you explain a bit more? You shouldn't have to build anything. conda installs prebuilt binaries.

Oh, are you on Windows? I think PETSc doesn't install there.
